package org.nipu.jmt.account;

import org.junit.Test;
import org.nipu.jmt.Result;

import java.math.BigDecimal;

import static org.junit.Assert.*;

/**
 * TODO: This is autogenerated Java-Doc.
 *
 * @author Nikita_Puzankov
 */
public class AtomicAccountTest {

    private final String testCustomerName = "test customer";

    @Test
    public void withdrawMoney() {
        final AtomicAccount atomicAccount = new AtomicAccount(testCustomerName);
        final Result<Account, AccountError> result = atomicAccount.withdrawMoney(BigDecimal.valueOf(100L));
        assertEquals(BigDecimal.valueOf(-100L), atomicAccount.getBalance());
        assertTrue(result.getValue().isPresent());
        assertFalse(result.getError().isPresent());
    }

    @Test
    public void withdrawNegativeAmountOfMoneyShouldReturnAnAccountError() {
        final AtomicAccount atomicAccount = new AtomicAccount(testCustomerName);
        final Result<Account, AccountError> result = atomicAccount.withdrawMoney(BigDecimal.valueOf(-100L));
        assertEquals(BigDecimal.ZERO, atomicAccount.getBalance());
        assertFalse(result.getValue().isPresent());
        assertTrue(result.getError().isPresent());
    }

    @Test
    public void putMoney() {
        final AtomicAccount atomicAccount = new AtomicAccount(testCustomerName);
        final Result<Account, AccountError> result = atomicAccount.putMoney(BigDecimal.valueOf(100L));
        assertEquals(BigDecimal.valueOf(100L), atomicAccount.getBalance());
        assertTrue(result.getValue().isPresent());
        assertFalse(result.getError().isPresent());
    }

    @Test
    public void putNegativeAmountOfMoneyShouldReturnAnAccountErro() {
        final AtomicAccount atomicAccount = new AtomicAccount(testCustomerName);
        final Result<Account, AccountError> result = atomicAccount.putMoney(BigDecimal.valueOf(-100L));
        assertEquals(BigDecimal.ZERO, atomicAccount.getBalance());
        assertFalse(result.getValue().isPresent());
        assertTrue(result.getError().isPresent());
    }

    @Test
    public void getBalance() {
        final AtomicAccount atomicAccount = new AtomicAccount(testCustomerName);
        assertEquals(BigDecimal.ZERO, atomicAccount.getBalance());
    }
}