package org.nipu.jmt.account;

import org.nipu.jmt.Result;

import java.math.BigDecimal;

/**
 * TODO: This is autogenerated Java-Doc.
 *
 * @author Nikita_Puzankov
 */
public interface Account {
    Result<Account, AccountError> withdrawMoney(BigDecimal amount);

    Result<Account, AccountError> putMoney(BigDecimal amount);

    BigDecimal getBalance();
}
